# =======================================================
#      APPLICATION.YAML (Base / Shared Settings)
#    - Sets the default active profile to 'dev'.
#    - Contains properties shared by all environments.
# =======================================================
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.hibernate.orm.connections.pooling: WARN

application:
  security:
    jwt:
      secret-key: "pJ3E/WC+7uYs6zvfs27nzxj+kDHC9aOt+FeZVYdqIxg="
      expiration: 2592000000 # 30 Tage in Milliseconds

spring:
  # Set 'dev' as the default profile. If no profile is set, the dev-settings will be loaded.
  profiles:
    active: dev