# =======================================================
#     APPLICATION-DEV.YAML (Development Profile)
#    - Enables H2 console and ddl-auto: update.
# =======================================================
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:file:./data/sundenbock-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false # use true if console logs of db are wanted
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true # H2 Console is enabled for development

server:
  port: 8080